### ISSUE TITLE
Graphing multiple subsets

### ISSUE THREAD

**Issue by SeanGallagher123** [STAT-ATA-ASU/DiscussionSTT2810#10]
My dataset is NESARC
I am having difficulty locating the information necessary to graph multiple subsets on the same barplot, with three separate bars. There are three subsets and the common factors between the three of them are: CONSUMER == 1 (if they are actively drinking alcohol), and if they were in college during the 2000 and 2001 school year. The other factors that are unique to each subset include one of the following: If the participant was raised by Foster Parents, Adoptive Parents or Relatives. 
I am able to graph each subset, but only one bar appears and I would like to show visual differences by combining the three. 
I would appreciate any assistance. @alanarnholt

**Comment by alanarnholt** [comment]
For some reason the tag did not go through.  I must be something on my end.  I will investigate...Thanks for posting.

Please post your code so we can be of more assistance.
