### ISSUE TITLE
Making a histogram using AddHealth

### ISSUE THREAD

**Issue by oliviaherder** [STAT-ATA-ASU/DiscussionSTT2810#11]
Hi! I am using Add Health and trying to make a histogram. I stopped by your office and we found the weight variable from Add Health to use for the histogram. I tried putting it in my code but I get an error saying that "x must be numeric". Is anyone else having this problem? What should I do? @alanarnholt

**Comment by alanarnholt** [comment]
For some reason I did not see this earlier.  My bad.  You may have converted your variable to a factor.  Try using hist(as.numeric(DF$YourVar))
