### ISSUE TITLE
Getting rid of scientific notation

### ISSUE THREAD

**Issue by joshpguerra** [STAT-ATA-ASU/DiscussionSTT2810#12]
I'm having trouble getting rid of scientific notation in my plots, I've tried options(scipen=999). I haven't been able to get it to work.

**Comment by alanarnholt** [comment]
Josh,

Make sure you tag me so I get an email if you want to get my attention.  Can you post your code or send a link to the problem  code and I will take a look.

**Comment by alanarnholt** [comment]
Try something like the following:

    library(PDS)
    head(gapminder)
    library(ggplot2)
    ggplot(data = gapminder, aes(x = co2emissions)) + geom_histogram()
    options(scipen = 9999)
    ggplot(data = gapminder, aes(x = co2emissions)) + geom_histogram()

This gets rid of the scientific notation on the x-axis.
