### ISSUE TITLE
Poster

### ISSUE THREAD

**Issue by hayeske** [STAT-ATA-ASU/DiscussionSTT2810#13]
How do we insert our graphs from r into power point? Are there instructions on git hub? Thanks.

**Comment by alanarnholt** [comment]
Kelsey...sorry I missed this one.  I think we answered this in class for you....correct?  If not I can write something here.  To make sure I see questions, please tag me with @alanarnholt .... or else I might not look here.  :)

**Comment by hayeske** [comment]
Hello,
Are you talking about the thing I posted on the git hub page last week? I
am pretty sure you have already responded to all of my emails.
Thanks and have a blessed evening,
Kelsey Hayes
