### ISSUE TITLE
Printing in the library

### ISSUE THREAD

**Issue by erinkreiling** [STAT-ATA-ASU/DiscussionSTT2810#14]
http://technews.library.appstate.edu/large-format-printing-services-at-tech-desk/
Here is the URL for instructions of how to print your poster in the library on campus. Unfortunately it costs about the same amount as every where else. The only drawback is you can only pay with an AppCard, but it may be more convenient for everyone. Especially if you do not have a car.

**Comment by alanarnholt** [comment]
Or as several students have told me if you have money on your app card and do not use it you lose it... :(
