### ISSUE TITLE
Methods

### ISSUE THREAD

**Issue by huertact** [STAT-ATA-ASU/DiscussionSTT2810#6]
Is anyone else having an extremely difficult time locating the information of how GapMinder conducted research?

**Comment by alanarnholt** [comment]
For those using the gapminder data set, you will most likely want to supplement your variables with information from the World Bank.  Use the WDI package and the function WDIsearch() to find variables relevant to your area.  I have found the best way to find information on the World Bank page is not to use the search engine in the World Bank.  Type the variable name in google...The World Bank describes where their information comes from....
