### ISSUE TITLE
Data Sets

### ISSUE THREAD

**Issue by erinkreiling** [STAT-ATA-ASU/DiscussionSTT2810#7]
In case anyone is having issues finding the codebooks, here is the link:
http://www1.appstate.edu/~arnholta/classes/PDS/

**Comment by alanarnholt** [comment]
This is a duplicate of https://github.com/STT2810-SP15/DiscussionSTT2810/issues/1

**Comment by alanarnholt** [comment]
Please remember to look in closed issues as well....this was the very first issue of the class https://github.com/STT2810-SP15/DiscussionSTT2810/issues/1

**Comment by erinkreiling** [comment]
Some students were still confused, so I wanted to repost it.

**Comment by alanarnholt** [comment]
I understand....this may be a good opportunity to show everyone how to look in the closed issues as well :) .... as many interesting issues will end of being closed just like this issue.
