### ISSUE TITLE
Data Management Due date

### ISSUE THREAD

**Issue by hayeske** [STAT-ATA-ASU/DiscussionSTT2810#8]
Since class was canceled this morning, will our data management assignment still be due this Friday?

**Comment by alanarnholt** [comment]
Yes.

**Comment by hayeske** [comment]
Hello,
Is there a reason that I am receiving emails for STT2810?
Thanks so much and have a blessed day,
Kelsey Hayes

**Comment by alanarnholt** [comment]
Dear Kelsey,

Yes....I just closed an old issue you had opened and more than likely you
had your account set to automatically receive an email with any updates.

Best,

Alan T. Arnholt
Professor
Department of Mathematical Sciences
Appalachian State University
T:(828)262-2863
F:(828)265-8617
http://www1.appstate.edu/~arnholta/
